### PR TITLE
Github workflow: Sticky to ubuntu 24.04 for CI

### PR DESCRIPTION
**Pull request by mukeshpanchal27**
## Summary

Sticky to ubuntu version 24.04 as ubuntu-latest will start to use 24.04 mentioned [here](https://github.com/actions/runner-images/issues/10636)

## Screenshot
Screenshot 2024-12-11 at 10 35 11 AM

### CODE REVIEW

**Comment by swissspidy** [comment]
What‘s wrong with Ubuntu 24? Can‘t we stay on the latest and greatest?

**Comment by mukeshpanchal27** [comment]
> What‘s wrong with Ubuntu 24? Can‘t we stay on the latest and greatest?

Updated to 24.04.

**Comment by swissspidy** [comment]
But why stick to Ubuntu 24 when ubuntu-latest will automatically update to v24 soon?

From what I can see, no action is required from us. GitHub is simply telling us that they will soon update their Ubuntu version.

**Comment by mukeshpanchal27** [comment]
Many folks are updating `ubuntu-latest` to `ubuntu-24.04`, so I went ahead and tested it in our repository. Everything seems to be working fine with no errors. ✅  

If no further action is needed, can I go ahead and close this issue?

**Comment by swissspidy** [comment]
That would be my recommendation, yes

**Pull request closed without merging**
