### PR TITLE
Refresh feature branch with `trunk` (due to unit test failures fixed)

### PR DESCRIPTION
**Pull request by felixarntz**
## Summary

Mostly relevant because of the fix in #881 that was merged into `trunk`.

## Checklist

- [x] PR has either `[Focus]` or `Infrastructure` label.
- [x] PR has a `[Type]` label.
- [x] PR has a milestone or the `no milestone` label.

### CODE REVIEW

**Review by swissspidy — APPROVED** [review]
Why not just push directly? Creating a PR for that is rather unusual.

**Comment by westonruter** [comment]
> Why not just push directly? Creating a PR for that is rather unusual.

I was just going to raise this point. Currently branch protections are blocking any direct pushes to feature branches. This adds too much friction, IMO. I think feature branch pushes should be allowed.

**Comment by felixarntz** [comment]
@swissspidy It's not possible because of branch protections, see Weston's comment.

@westonruter I agree it's not ideal, let's discuss how we can improve it without giving up branch protection completely. In the meantime, we can probably still merge this?

**Comment by swissspidy** [comment]
> I agree it's not ideal, let's discuss how we can improve it without giving up branch protection completely

Well you can specify which branches should be protected with glob patterns. Only `trunk` and `release/*` really need to be protected.

**Comment by felixarntz** [comment]
@swissspidy It's not that simple. Sure, we could do that, but branch protection is also to prevent accidental deletion, e.g. relevant for the configuration for automatically deleting PR branches.

If this branch protection of feature branches leads to more headaches than it helps, we can consider getting rid of it, but that does not only come with benefits - otherwise we would have never enabled it in the first place.

**Review by westonruter — APPROVED** [review]

**Comment by westonruter** [comment]
Branch protection can be enabled to prevent deletion without also blocking pushes.

**Pull request merged**
