### PR TITLE
Remove unnecessary leftover CSS for dominant color backgrounds on images

### LINKED ISSUE #562: With Dominant Color enabled, loses focal point settings
## Bug Description

When the Dominant Color is enabled in the performance plug-in the image looses its focal point

## Steps to reproduce

1. make sure Dominant Color is enabled in performance plug-in
2. Go to a page or post
3. add a cover to the post/page
4. set a focal point
5. update image and see the image just centering
6. disable Dominant Color and reload page/post
7. the focal point set in admin is used

## Additional Context

 - PHP Version: 7.4.32 
 - OS: MacOS
 - Browser: Chrome
 - Plugin Version: 1.6.0
 - Device: MacBook pro m1 pro

### PR DESCRIPTION
**Pull request by pbearne**
## Summary

~~Fixes #562~~

## Checklist

- [x] PR has either `[Focus]` or `Infrastructure` label.
- [x] PR has a `[Type]` label.
- [x] PR has a milestone or the `no milestone` label.

### CODE REVIEW

**Comment by costdev** [comment]
[A recent commit](https://github.com/WordPress/performance/commit/03b13e5d606c007818424f3571d274b3649e8594) resolves the missing class in the test failures. This should be resolved after rebasing this branch on `trunk`/merging `trunk` into this branch.

**Review by felixarntz — COMMENTED** [review]
@pbearne +1 to what @costdev says. This is good to approve once you've merged `trunk` back into this so that the unit tests should pass again.

**Review by mukeshpanchal27 — COMMENTED** [review]
The users' complaint about the focal point is not addressed by this adjustment. The line in the code at https://github.com/WordPress/performance/blob/trunk/modules/images/dominant-color/load.php#L130 overrides any custom CSS that the focus point added, such as `object-position: 45% 0%;`.

**Comment by felixarntz** [comment]
@mukeshpanchal27 Good catch! I hadn't paid attention to what the concrete issue was about here.

@pbearne Per the above, and since between #578 and #582 that problem is actually fixed, I'll close this PR.

**Pull request closed without merging**
