### PR TITLE
Dominant Color: GIF images always being flagged as having transparency.

### LINKED ISSUE #405: Dominant Color: GIF images always being flagged as having transparency.
## Bug Description

GIF images always being flagged as having transparency.  

## Additional Context

 - PHP Version: 
 - Browser: [e.g. chrome, safari]
 - Plugin Version: [e.g. 22]

### PR DESCRIPTION
**Pull request by spacedmonkey**
## Summary

Turns out the fixture data was wrong and encoding incorrectly. 
Fixes #405

## Checklist

- [x] PR has either `[Focus]` or `Infrastructure` label.
- [x] PR has a `[Type]` label.
- [x] PR has a milestone or the `no milestone` label.

### CODE REVIEW

**Review by pbearne — APPROVED** [review]
well spotted

**Comment by spacedmonkey** [comment]
@adamsilverstein @felixarntz Can I get an approval here. This is a fix for unit tests.

**Review by adamsilverstein — APPROVED** [review]
Great!

**Review by felixarntz — APPROVED** [review]
Great catch!

**Pull request merged**
