### PR TITLE
Use `assertStringContainsString` instead of `assertContains` to fix PHPUnit deprecation warnings

### LINKED ISSUE #594: Use `assertStringContainsString` instead of `assertContains` to fix PHPUnit deprecation warnings
See https://github.com/WordPress/performance/actions/runs/3678224462/jobs/6221219652#step:8:67 for example. `assertContains` should not be used with strings. `assertStringContainsString` needs to be used instead.

### PR DESCRIPTION
**Pull request by mukeshpanchal27**
## Summary

The PR fixes PHPUnit deprecation warnings and uses `assertStringContainsString` instead of `assertContains` and `assertStringNotContainsString` instead of `assertNotContains`.

Fixes #594

## Checklist

- [x] PR has either `[Focus]` or `Infrastructure` label.
- [x] PR has a `[Type]` label.
- [x] PR has a milestone or the `no milestone` label.

### CODE REVIEW

**Comment by mukeshpanchal27** [comment]
There is one more waring in unit tests [Details](https://github.com/WordPress/performance/actions/runs/3682616869/jobs/6230395936) that needs to addressed.

```
Warning: file_put_contents(/var/www/html/wp-content/plugins/performance/.phpunit.result.cache): failed to open stream: 
Permission denied in phar:///usr/local/bin/phpunit/phpunit/Runner/DefaultTestResultCache.php on line 111
```

**Comment by mukeshpanchal27** [comment]
@felixarntz @aaemnnosttv I'd like to get your feedback on this. I'm still keeping it as a draft PR until I have find a solution for this notice.

**Comment by felixarntz** [comment]
@mukeshpanchal27 Thank you for the PR. Regarding the other warning about `file_put_contents`, let's treat that separately. This issue was only focused on the warnings triggered by our tests themselves. I think the other one you've discovered is related to the overall configuration of the testing environment, and it's not caused by this PR, so we can fix it separately.

Can you open an issue for us to work on that please so we can explore further?

**Review by felixarntz — APPROVED** [review]
Looks great!

**Review by mitogh — APPROVED** [review]

**Pull request merged**
