### PR TITLE
Create Queue Admin Screen

### LINKED ISSUE #491: Create Background Processing Infrastructure: Create Queue Admin Screen
Create a basic queue admin screen to display a list of all jobs. This will make use of the default taxonomy admin screen but made read only by removing the create/edit functionality. This screen will be used by developers for debugging and will not be made visible by default. A filter will be created to allow developers to enable the screen when required.

## Acceptance Criteria
- Utilise the existing taxonomy screen for the `background_job` taxonomy
- Disable user creating/editing and deleting of jobs by assigning custom capabilities to the `background_job` taxonomy
- Create a `perflab_enable_background_process_queue_screen` filter used to hide/show the admin screen
- The admin screen is disabled by default

### PR DESCRIPTION
**Pull request by ankitrox**
## Summary

Create an admin screen for managing the jobs in the queue. This is technically managing the terms in `background_job` taxonomy.

Fixes #491 

## Relevant technical choices

1. Add custom menu under `tools.php`
2. Customise WP_List_Table to add custom items.

## Checklist

- [x] PR has either `[Focus]` or `Infrastructure` label.
- [x] PR has a `[Type]` label.
- [x] PR has a milestone or the `no milestone` label.

### CODE REVIEW

**Comment by ankitrox** [comment]
~~This can be reviewed once the background job class have been merged in feature branch~~

**Comment by ankitrox** [comment]
screenshot-localhost_8888-2022 09 20-21_35_03

Added the placeholder labels for terms. Dynamic labels will be added once the background job class [PR](https://github.com/WordPress/performance/pull/507) gets merged.

CC: @felixarntz @jjgrainger

**Comment by ankitrox** [comment]
### Self Note

1. Replace all instances of `background_job` with `PERFLAB_BACKGROUND_JOB_TAXONOMY_SLUG` constant.  :white_check_mark:
2. Replace get_term_meta calls with proper method by instantiating job object.

**Comment by swissspidy** [comment]
Closing for now to clean up the repo since this plugin/module is not a priority right now.

**Pull request closed without merging**
