### PR TITLE
Merge initial accurate sizes work into trunk

### PR DESCRIPTION
**Pull request by mukeshpanchal27**
The PR merge the initial set of work for accurate sizes to the trunk for release.

Initial feature release issues:
- [x] #1187
- [x] #1251
- [x] #1289
- [x] #1330

### CODE REVIEW

**Review by joemcgill — CHANGES_REQUESTED** [review]
Thanks for getting this open. Leaving a review to mark this as blocked until all of the planned work on this feature for v1 is completed.

**Comment by mukeshpanchal27** [comment]
@joemcgill @westonruter @swissspidy The PR is ready for review. The version bump and changelog is part of #1332. Can we merge this today, please?

**Review by swissspidy — APPROVED** [review]

**Comment by westonruter** [comment]
@joemcgill Is this PR still blocked from merging?

@mukeshpanchal27 I've updated the issues and PRs related to this PR to ensure they are all milestoned for `auto-sizes 1.1.0` and have the appropriate labels.

**Review by joemcgill — APPROVED** [review]
I think this is good to merge into trunk and iterate from there.

**Pull request merged**
