### PR TITLE
Added global documentation

### LINKED ISSUE #1003: Need to Add Global Documentation in plugins.php file
Need to add Global Documentation according to [PHP Documentation Standards](https://developer.wordpress.org/coding-standards/inline-documentation-standards/php/)  in below file.

**1. admin/plugins.php file**

### PR DESCRIPTION
**Pull request by keyurptl**
Added Global documentation according to [PHP Documentation Standards.](https://developer.wordpress.org/coding-standards/inline-documentation-standards/php/)

Fixes: https://github.com/WordPress/performance/issues/1003

### CODE REVIEW

**Review by westonruter — APPROVED** [review]

**Review by mukeshpanchal27 — CHANGES_REQUESTED** [review]
Thanks, @keyurptl, for the PR. We don't need this global variable as it will not be used on the page. Instead of adding the document, we should remove it from the code.

Please correct me if I missed anything. Thank you!

**Comment by keyurptl** [comment]
> Thanks, @keyurptl, for the PR. We don't need this global variable as it will not be used on the page. Instead of adding the document, we should remove it from the code.
> 
> Please correct me if I missed anything. Thank you!

@mukeshpanchal27 Thanks for the feedback.

I have updated changes as per mentioned.

**Review by felixarntz — APPROVED** [review]
Thank you @keyurptl!

**Review by mukeshpanchal27 — APPROVED** [review]
Thanks @keyurptl for the updates. LGTM!

**Pull request merged**
