### PR TITLE
Merge trunk into feature/image-loading-optimization

### PR DESCRIPTION
**Pull request by westonruter**
Feature branch is getting stale. No need to look at the code as this is simply doing:

```
git merge trunk
npm install --package-lock-only
```

The latter is to fix merge conflicts in `package-lock.json`.

### CODE REVIEW

**Review by joemcgill — APPROVED** [review]
Not sure what's going on with the sniffs here, given this is already all in trunk.

**Comment by westonruter** [comment]
> Not sure what's going on with the sniffs here, given this is already all in trunk.

Oh yes. The issue there is that JS linting is currently not being done on anything other than `bin`. I fixed this in the feature branch but I haven't done it yet in `trunk`:

image

I'll open a PR to do that as well.

**Review by swissspidy — APPROVED** [review]

**Review by felixarntz — APPROVED** [review]

**Comment by westonruter** [comment]
> I'll open a PR to do that as well.

See https://github.com/WordPress/performance/pull/930

**Review by mukeshpanchal27 — APPROVED** [review]

**Comment by mukeshpanchal27** [comment]
Now that #930 has been merged, it's necessary to rebase this branch to ensure that the JS linting passes successfully.

**Pull request merged**
