### PR TITLE
Fix invalid docs and return types as highlighted by static analysis

### LINKED ISSUE #622: Benefit from static analysis
## Bug Description

There are errors in the code.
e.g. `webp_uploads_update_image_onchange`: _Callback expects 5 parameters, $accepted_args is set to 7._

## Steps to reproduce

1. `composer require --dev szepeviktor/phpstan-wordpress`
2. `vendor/bin/phpstan analyse -c vendor/szepeviktor/phpstan-wordpress/extension.neon admin/ modules/ server-timing/ *.php --level=0` then raise level by one
3. Benefit!

Please consider using PHPStan.
Thank you!

### PR DESCRIPTION
**Pull request by kt-12**
## Summary

Fixes #622

Fix issues with doc type and return that was throwing error in static test.

## Checklist

- [x] PR has either `[Focus]` or `Infrastructure` label.
- [x] PR has a `[Type]` label.
- [x] PR has a milestone or the `no milestone` label.

### CODE REVIEW

**Review by felixarntz — APPROVED** [review]
@kt-12 Thanks, LGTM!

**Comment by felixarntz** [comment]
@aristath This fixes a few minor things in the SQLite module, so I wanted to make sure you see this. Right now we're in a bit of an unfortunate situation of having the code duplicated, so can you make sure to address this in your plugin as well? Should be a quick fix. (The return types need to align with the parent classes, for example.)

**Comment by felixarntz** [comment]
@mukeshpanchal27 Can you give this a 2nd review and approval please?

**Review by mukeshpanchal27 — APPROVED** [review]
Thanks @kt-12, The changes look good to me!

**Comment by aristath** [comment]
Backported to the standalone plugin as well 👍

**Pull request merged**
