### PR TITLE
Updated npm dependencies to their latest versions to fix vulnerability issues.

### LINKED ISSUE #510: Update npm dependencies to the latest versions to fix vulnerability issues reported by npm
## Feature Description

Npm audit report shows that we have 7 high vulnerabilities in dependency packages:

```
found 10 vulnerabilities (3 moderate, 7 high) in 1623 scanned packages
```

We need to update all dependencies to the latest versions to fix vulnerabilities. If it doesn't help, we will need to follow instructions provided by `npm audit` command to fix remaining issues.

We should also consider adding the `prettier` dependency to the dependencies list and remove it from the peer dependencies because some folks have issues caused by missing prettier dependency when they run the `lint-js` command.

### PR DESCRIPTION
**Pull request by eugene-manuilov**
## Summary

Fixes #510

## Checklist

- [x] PR has either `[Focus]` or `Infrastructure` label.
- [x] PR has a `[Type]` label.
- [x] PR has a milestone or the `no milestone` label.

### CODE REVIEW

**Review by felixarntz — APPROVED** [review]
@eugene-manuilov Great, thank you!

**Review by mukeshpanchal27 — APPROVED** [review]
LGTM.

**Comment by mukeshpanchal27** [comment]
> We should also consider adding the `prettier` dependency to the dependencies list and remove it from the peer dependencies because some folks have issues caused by missing prettier dependency when they run the `lint-js` command.

FYI, `Prettier` is in the list of dependencies of the `lint-staged` [package](https://www.npmjs.com/package/lint-staged).

**Comment by eugene-manuilov** [comment]
> > We should also consider adding the `prettier` dependency to the dependencies list and remove it from the peer dependencies because some folks have issues caused by missing prettier dependency when they run the `lint-js` command.
> 
> FYI, `Prettier` is in the list of dependencies of the `lint-staged` [package](https://www.npmjs.com/package/lint-staged).

@mukeshpanchal27, `lint-staged` uses `prettier` as a development dependency which is not installed with the package. Currently we use prettier which is installed with `@wordpress/scripts`, you can see it if you run `npm ls prettier` in your terminal.

**Comment by mukeshpanchal27** [comment]
> Currently we use prettier which is installed with `@wordpress/scripts`, you can see it if you run `npm ls prettier` in your terminal.

Thanks for the information.

**Pull request merged**
