### PR TITLE
Add consistent unit test naming

### LINKED ISSUE #514: Consistency in unit tests
## Bug Description
We should follow the consistency in the unit tests. Some tests use `@test` annotation and some functions don't use it. Instead, they use `test_*` in the function name. Most of our unit tests use `@test` annotation.

## Steps to reproduce

https://github.com/WordPress/performance/blob/0a9570795dbc602cbc305d2b47b3a5a589f547cd/tests/plugins/webp-uploads/helper-tests.php#L17

### PR DESCRIPTION
**Pull request by AhmarZaidi**
Fixes #514

## Summary

For webp-uploads tests:
- [x] Remove `@test` annotations from function doc block comments.
- [x] Add `test_*` prefix in all PHPUnit test functions. 

This change standardizes the test function naming convention across the file and ensures consistency in unit test naming. 

## Relevant technical choices

NA

### CODE REVIEW

**Comment by AhmarZaidi** [comment]
@thelovekesh Some check are failing due to missing labels, but I can't add labels to the PR.

**Comment by westonruter** [comment]
@AhmarZaidi I've added the necessary labels.

**Comment by westonruter** [comment]
Looks like the following files still have `@test`:

* `plugins/webp-uploads/image-edit-tests.php`
* `plugins/webp-uploads/load-tests.php`
* `plugins/webp-uploads/rest-api-tests.php`

**Comment by AhmarZaidi** [comment]
> Looks like the following files still have `@test`:
> 
>     * `plugins/webp-uploads/image-edit-tests.php`
> 
>     * `plugins/webp-uploads/load-tests.php`
> 
>     * `plugins/webp-uploads/rest-api-tests.php`

Addressed here: https://github.com/WordPress/performance/pull/1246/commits/b629e649608ca5b7b6c3edee6232efc8b191d5c9

**Comment by westonruter** [comment]
Looking good! Ready for review?

**Review by westonruter — APPROVED** [review]

**Pull request merged**
