### PR TITLE
Improve docs in speculative loading plugin readme

### LINKED ISSUE #1459: Speculative Loading readme needs improvement
## Feature Description

See feedback from @felixarntz in https://github.com/WordPress/performance/pull/1155#pullrequestreview-2222128866

A [Google Doc](https://docs.google.com/document/d/1cQQG7WUCJolqwdWHSIuj1D05AFHLCdaPUIA1uyNJk0g/edit?usp=drivesdk&resourcekey=0-7L9olr8TFD2oPzw701Warg) has been shared for collaboration.

### PR DESCRIPTION
**Pull request by felixarntz**
## Summary

Updates the Speculative Loading readme based on the changes from [the doc](https://docs.google.com/document/d/1cQQG7WUCJolqwdWHSIuj1D05AFHLCdaPUIA1uyNJk0g/edit)

Fixes #1459

### CODE REVIEW

**Review by westonruter — APPROVED** [review]
LGTM!

**Comment by westonruter** [comment]
We'll wait to merge this until Monday for some final suggestions from @tunetheweb.

**Comment by tunetheweb** [comment]
Made some final suggestions in the doc.

**Comment by mukeshpanchal27** [comment]
> Updates the Speculative Loading readme based on the changes from [the doc](https://docs.google.com/document/d/1cQQG7WUCJolqwdWHSIuj1D05AFHLCdaPUIA1uyNJk0g/edit)

The doc is not accessible.

**Comment by felixarntz** [comment]
Thanks @tunetheweb! I'll open a PR with them shortly.

@mukeshpanchal27 Apologies, I hadn't noticed that. I'd normally make it public now, but there's not really anything more to discuss on it, so I'll just open the PR, which will include all remaining changes from the doc.

**Comment by westonruter** [comment]
@felixarntz I think the changes can be added to this existing PR?

**Comment by felixarntz** [comment]
In https://github.com/WordPress/performance/pull/1638/commits/417936258e968976fa45d2a9d8c5552fa45e420e I've included the additional changes from @tunetheweb.

**Review by westonruter — APPROVED** [review]

**Review by tunetheweb — APPROVED** [review]

**Comment by westonruter** [comment]
README updates have been deployed: https://wordpress.org/plugins/speculation-rules/

**Pull request merged**
